# Use PHP-Apache base image
services:
    web:
     build:
       context: .
       dockerfile: Dockerfile
     volumes: 
       - ./site:/var/www/html
     ports:
       - "80:80"
     depends_on:
       - db
  
    db:
      image: mysql
      restart: always
      volumes:
       - db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123
  
    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
      depends_on:
       -db
        
volumes:
   db: