version: '3'
services:
  web:
    image: php:7.4-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database:/var/lib/mysql
